server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: CourseRegistrationSystem
          uri: http://localhost:8081
          predicates:
            - Path=/courseRegistrationSystems/** 
        - id: LectureSystem
          uri: http://localhost:8082
          predicates:
            - Path=/lectureSystems/** 
        - id: PaymentSystem
          uri: http://localhost:8083
          predicates:
            - Path=/paymentSystems/** 
        - id: DashBoard
          uri: http://localhost:8084
          predicates:
            - Path= /courseRegistrationStatuses/**/lecturerStatuses/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: CourseRegistrationSystem
          uri: http://CourseRegistrationSystem:8080
          predicates:
            - Path=/courseRegistrationSystems/** 
        - id: LectureSystem
          uri: http://LectureSystem:8080
          predicates:
            - Path=/lectureSystems/** 
        - id: PaymentSystem
          uri: http://PaymentSystem:8080
          predicates:
            - Path=/paymentSystems/** 
        - id: DashBoard
          uri: http://DashBoard:8080
          predicates:
            - Path= /courseRegistrationStatuses/**/lecturerStatuses/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
